### ISSUE TITLE
FDDB lookup fails: minor link format changes?

### ISSUE THREAD

**Issue by 229c9cf0** [blinry/nom#12]
Hi!

```
ratzon/tty4/nobody ~ $ nom mate
Previous log entries:
    (75) 2022-09-18 lamate
   (100) 2022-09-18 kolle-mate
    (50) 2022-09-18 charitea mate
    (75) 2022-09-19 lamate
---------------------
   (300) total

/usr/lib/ruby/2.5.0/open-uri.rb:37:in `initialize'
/usr/lib/ruby/2.5.0/open-uri.rb:37:in `open'
/usr/lib/ruby/2.5.0/open-uri.rb:37:in `open'
/var/lib/gems/2.5.0/gems/nom-0.1.3/lib/nom/nom.rb:115:in `block in search'
/var/lib/gems/2.5.0/gems/nom-0.1.3/lib/nom/nom.rb:114:in `each'
/var/lib/gems/2.5.0/gems/nom-0.1.3/lib/nom/nom.rb:114:in `search'
/var/lib/gems/2.5.0/gems/nom-0.1.3/bin/nom:61:in `<top (required)>'
/usr/local/bin/nom:23:in `load'
/usr/local/bin/nom:23:in `<main>'
No such file or directory @ rb_sysopen - /db/de/lebensmittel/brauerei_loscher_club_mate/index.html
Something went wrong. Usage of this command is: nom search <term>
[0]
```

From some quick experimenting, it seems

```diff
<                 page = Nokogiri::HTML(open(result))
>                 page = Nokogiri::HTML(open("http://fddb.info/" + result))
```

is all it takes to fix this, but I know zero Ruby, so I'm not confident this is idiomatic or even fully correct.

Cheers!

**Comment by blinry** [comment]
Thanks for finding out the cause! :)
